name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Adjust this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t tanzwutgandalf/demo:latest .

      - name: Push the Docker image
        run: |
          docker push tanzwutgandalf/demo:latest
